language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gpyanev/docker-react-template -f Dockerfile.dev .

script:
  - docker run -e CI=true gpyanev/docker-react-template npm run test
